I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/glugagonScript.rpy", line 188, in script
    if needHelp == True:
  File "game/glugagonScript.rpy", line 188, in <module>
    if needHelp == True:
NameError: name 'needHelp' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/glugagonScript.rpy", line 188, in script
    if needHelp == True:
  File "/Users/maheenkhan/Desktop/CSFiles/VIP/renpy-8.2.1-sdk/renpy/ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "/Users/maheenkhan/Desktop/CSFiles/VIP/renpy-8.2.1-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/maheenkhan/Desktop/CSFiles/VIP/renpy-8.2.1-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/glugagonScript.rpy", line 188, in <module>
    if needHelp == True:
NameError: name 'needHelp' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.2.1.24030407
Serious Games 1.8
Sat Apr 20 09:12:08 2024
