I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 88, in script
    b "Oh yeah, I’m all good. Thanks for asking. Just tired after the workout and weirdly anxious about the project"
Exception: Sayer 'b' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 88, in script
    b "Oh yeah, I’m all good. Thanks for asking. Just tired after the workout and weirdly anxious about the project"
  File "C:\Users\jliao\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\jliao\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'b' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Serious Games 1.0
Wed Nov 30 17:55:02 2022
